-- ════════════════════════════════════════════════════════════════════════════
-- FORTIZED × SWIFTAW CLOUD INTEGRATION
-- Database Migration: Cloud Authentication Schema
-- ════════════════════════════════════════════════════════════════════════════

-- ──────────────────────────────────────────────────────────────────────────
-- 1. ALTER USERS TABLE - Add Cloud integration columns
-- ──────────────────────────────────────────────────────────────────────────

ALTER TABLE users ADD COLUMN IF NOT EXISTS cloud_user_id UUID UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_linked_to_cloud BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMP WITH TIME ZONE;

-- ──────────────────────────────────────────────────────────────────────────
-- 2. CREATE CLOUD_ACCOUNT_LINKS TABLE
-- ──────────────────────────────────────────────────────────────────────────
-- Tracks Fortized subaccounts linked to Cloud users
-- This is the core table for multi-account management

CREATE TABLE IF NOT EXISTS cloud_account_links (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cloud_user_id UUID NOT NULL,
  fortized_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  subaccount_id UUID NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  linked_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  linked_by VARCHAR(50) DEFAULT 'cloud',  -- 'cloud', 'manual', 'auto'
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  -- Constraints: Only one subaccount ID per Cloud user, subaccount must be unique
  UNIQUE(cloud_user_id, subaccount_id),
  UNIQUE(subaccount_id),
  UNIQUE(username, cloud_user_id)
);

-- ──────────────────────────────────────────────────────────────────────────
-- 3. CREATE CLOUD_LINKING_TOKENS TABLE
-- ──────────────────────────────────────────────────────────────────────────
-- One-time tokens (5-min expiry) for existing users to link to Cloud
-- Used when: "Link existing Fortized account to Cloud"

CREATE TABLE IF NOT EXISTS cloud_linking_tokens (
  token VARCHAR(255) PRIMARY KEY,
  cloud_user_id UUID NOT NULL,
  fortized_user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expires_at TIMESTAMP WITH TIME ZONE,
  used_at TIMESTAMP WITH TIME ZONE,
  is_used BOOLEAN DEFAULT FALSE
);

-- ──────────────────────────────────────────────────────────────────────────
-- 4. INDEXES FOR PERFORMANCE
-- ──────────────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_users_cloud_user_id ON users(cloud_user_id);
CREATE INDEX IF NOT EXISTS idx_users_is_linked ON users(is_linked_to_cloud);
CREATE INDEX IF NOT EXISTS idx_cloud_links_cloud_user ON cloud_account_links(cloud_user_id);
CREATE INDEX IF NOT EXISTS idx_cloud_links_fortized_user ON cloud_account_links(fortized_user_id);
CREATE INDEX IF NOT EXISTS idx_cloud_links_subaccount ON cloud_account_links(subaccount_id);
CREATE INDEX IF NOT EXISTS idx_cloud_links_active ON cloud_account_links(cloud_user_id, is_active);
CREATE INDEX IF NOT EXISTS idx_cloud_tokens_cloud_user ON cloud_linking_tokens(cloud_user_id);
CREATE INDEX IF NOT EXISTS idx_cloud_tokens_used ON cloud_linking_tokens(is_used, expires_at);

-- ──────────────────────────────────────────────────────────────────────────
-- 5. NOTES FOR FORTIZED TEAM
-- ──────────────────────────────────────────────────────────────────────────
--
-- What changed:
-- ✅ users table: Added cloud_user_id, is_linked_to_cloud, last_login
-- ✅ New table: cloud_account_links (tracks all linked Fortized accounts per Cloud user)
-- ✅ New table: cloud_linking_tokens (one-time tokens for account linking)
-- ✅ Indexes: Performance optimized for Cloud queries
--
-- Important:
-- - Each Fortized user (subaccount) can be linked to ONE Cloud account
-- - Each Cloud account can have UP TO 10 Fortized subaccounts
-- - Linking is 1:1 (one Fortized user → one Cloud user)
-- - But 1:Many (one Cloud user → many Fortized users)
--
-- When to use which table:
-- - users: Traditional Fortized login + Cloud linkage metadata
-- - cloud_account_links: Query all Fortized accounts for a Cloud user
-- - cloud_linking_tokens: Generate one-time linking codes for existing users
--
-- ──────────────────────────────────────────────────────────────────────────
